### ISSUE TITLE
Jessie is being abandoned - sources.list updated

### ISSUE THREAD

**Issue by david-duncan** [mysqlboy/docker-mydumper#3]
Any downstream images that rely on apt update behavior are failing.

Short term - need to get a new build of this image going, debian team fixed this upstream so a new build should grab latest jessie-slim 

https://github.com/debuerreotype/docker-debian-artifacts/issues/66

Long term - need to abandon jessie

/cc @mysqlboy

**Comment by mysqlboy** [comment]
Added multi build compatibility and bumped the Debian version.
